Funtion to upload the file to the bucket is working, extra changes ne…
JorgePAJ/Power-Dash pull request #32
Opened 2023-05-23 03:50 UTC by JorgeDCruz

…eded

2023-05-23 22:54 UTC, JorgePAJ requested changes
Se ve muy bien, no estoy seguro del funcionamiento yaque no lo he probado, pero te deje unos comentarios muy aparte de tu aportacion, buena we :D <3

2023-05-23 22:54 UTC, JorgePAJ commented on powerdash/.env
.env no debe estar en la repo, agregalo a tu gitignore

2023-05-23 22:54 UTC, JorgePAJ commented on powerdash/src/env.mjs
supongo que este archivo tampoco debe estar aqui????

2023-05-23 22:54 UTC, JorgePAJ commented on powerdash/src/pages/index.tsx
>      if(input !== null){
esto deberia de funcionar tambien :)
```if(input){```

2023-05-25 23:12 UTC, VicenteVieraG commented on powerdash/src/pages/index.tsx
>      if(input !== null){
Estos cambios fueron implementados en la branch de la searchbar en el pr #34

2023-05-31 00:23 UTC, merged